-- =====================================================================
--  CRM IAESTE — Esquema de base de datos (Supabase)
--
--  Crea las tablas, reglas de acceso (RLS), funciones y triggers que
--  necesita la app. No incluye datos: ni empresas ni usuarios.
--
--  Cómo usarlo:
--    1. Crea un proyecto nuevo en Supabase.
--    2. SQL Editor → New query → pega TODO este archivo → Run.
--    3. Authentication → Hooks → "Before User Created" → elige la función
--       public.hook_antes_de_crear_usuario y actívalo (bloquea emails
--       temporales; opcional, pero recomendado).
--    4. Despliega la app y regístrate: la PRIMERA cuenta que se registre
--       será admin automáticamente; las siguientes, miembros.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;


-- ---------------------------------------------------------------------
--  1. Tablas
-- ---------------------------------------------------------------------

-- Perfil de cada usuario (se crea solo al registrarse)
create table public.profiles (
  id      uuid primary key references auth.users (id) on delete cascade,
  nombre  text not null,
  rol     text not null default 'miembro' check (rol in ('miembro', 'admin')),
  creado  timestamptz not null default now()
);

-- Empresas a contactar
create table public.empresas (
  id                uuid primary key default gen_random_uuid(),
  nombre            text not null,
  cif               text default '',
  sector            text default '',
  contacto          text default '',
  email             text default '',
  telefono          text default '',
  direccion         text,
  responsable       uuid references public.profiles (id) on delete set null,
  estado            text not null default 'sin_contactar',
  notas             text default '',
  proximo_contacto  date,
  historica         boolean not null default false,
  actualizado       timestamptz not null default now(),
  actualizado_por   text default ''
);

create index empresas_responsable_idx on public.empresas (responsable);
create index empresas_estado_idx      on public.empresas (estado);

-- Opcional (recomendado): impide CIF repetidos. Ignora los vacíos.
-- create unique index empresas_cif_unico on public.empresas (upper(cif)) where coalesce(cif, '') <> '';

-- Historial de todo lo que pasa (de aquí salen los puntos)
create table public.historial (
  id               bigint generated by default as identity primary key,
  empresa_id       uuid references public.empresas (id) on delete set null,
  empresa_nombre   text not null default '',
  usuario_id       uuid references public.profiles (id) on delete set null,
  usuario_nombre   text not null default 'sistema',
  accion           text not null,
  detalle          text not null default '',
  estado_anterior  text,
  estado_nuevo     text,
  creado           timestamptz not null default now()
);

create index historial_empresa_idx on public.historial (empresa_id);
create index historial_usuario_idx on public.historial (usuario_id);
create index historial_creado_idx  on public.historial (creado);

-- Prácticas conseguidas por empresa y año (marcan la empresa como histórica)
create table public.practicas (
  id                 bigint generated by default as identity primary key,
  empresa_id         uuid not null references public.empresas (id) on delete cascade,
  anio               integer,
  num_practicas      integer,
  notas              text,
  creado             timestamptz not null default now(),
  creado_por         uuid default auth.uid(),
  creado_por_nombre  text
);

create index practicas_empresa_idx on public.practicas (empresa_id);

-- Dominios de email desechables que no pueden registrarse
create table public.dominios_bloqueados (
  dominio  text primary key,
  creado   timestamptz not null default now()
);

insert into public.dominios_bloqueados (dominio) values
  ('mailinator.com'), ('yopmail.com'), ('guerrillamail.com'), ('10minutemail.com'),
  ('tempmail.com'), ('temp-mail.org'), ('trashmail.com'), ('sharklasers.com'),
  ('getnada.com'), ('maildrop.cc'), ('dispostable.com'), ('throwawaymail.com')
on conflict do nothing;


-- ---------------------------------------------------------------------
--  2. Funciones auxiliares
-- ---------------------------------------------------------------------

-- ¿El usuario actual es admin?
create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and rol = 'admin'
  );
$$;

-- Crea el perfil al registrarse. La primera cuenta del CRM es admin.
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer
set search_path to 'public'
as $$
begin
  insert into public.profiles (id, nombre, rol)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nombre', split_part(new.email, '@', 1)),
    case when not exists (select 1 from public.profiles) then 'admin' else 'miembro' end
  );
  return new;
end;
$$;

-- Los miembros no pueden cambiar nombre, sector, responsable ni la marca de histórica
create or replace function public.empresas_guard()
returns trigger
language plpgsql security definer
set search_path to 'public'
as $$
begin
  if not public.is_admin() and coalesce(current_setting('crm.sistema', true), '') <> '1' then
    if new.nombre is distinct from old.nombre
       or new.sector is distinct from old.sector
       or new.responsable is distinct from old.responsable
       or new.historica is distinct from old.historica then
      raise exception 'Solo un admin puede modificar nombre, sector, responsable o la marca de histórica';
    end if;
  end if;
  new.actualizado := now();
  return new;
end;
$$;

-- Apunta en el historial cada alta, cambio de estado, nota, agenda, responsable y datos
create or replace function public.historial_log()
returns trigger
language plpgsql security definer
set search_path to 'public'
as $$
declare
  v_uid    uuid := auth.uid();
  v_nombre text;
  v_datos  text[] := '{}';
begin
  select nombre into v_nombre from public.profiles where id = v_uid;
  v_nombre := coalesce(v_nombre, nullif(new.actualizado_por, ''), 'sistema');

  if tg_op = 'INSERT' then
    insert into public.historial (empresa_id, empresa_nombre, usuario_id, usuario_nombre, accion, detalle, estado_nuevo)
    values (new.id, new.nombre, v_uid, v_nombre, 'alta', 'Empresa dada de alta', new.estado);
    return new;
  end if;

  if new.estado is distinct from old.estado then
    insert into public.historial (empresa_id, empresa_nombre, usuario_id, usuario_nombre, accion, detalle, estado_anterior, estado_nuevo)
    values (new.id, new.nombre, v_uid, v_nombre, 'estado', old.estado || ' → ' || new.estado, old.estado, new.estado);
  end if;

  if coalesce(new.notas, '') is distinct from coalesce(old.notas, '') and coalesce(new.notas, '') <> '' then
    insert into public.historial (empresa_id, empresa_nombre, usuario_id, usuario_nombre, accion, detalle)
    values (new.id, new.nombre, v_uid, v_nombre, 'nota', left(new.notas, 500));
  end if;

  if new.proximo_contacto is distinct from old.proximo_contacto then
    insert into public.historial (empresa_id, empresa_nombre, usuario_id, usuario_nombre, accion, detalle)
    values (new.id, new.nombre, v_uid, v_nombre, 'agenda',
            case when new.proximo_contacto is null then 'Recordatorio eliminado'
                 else 'Próximo contacto: ' || new.proximo_contacto::text end);
  end if;

  if new.responsable is distinct from old.responsable then
    insert into public.historial (empresa_id, empresa_nombre, usuario_id, usuario_nombre, accion, detalle)
    values (new.id, new.nombre, v_uid, v_nombre, 'responsable',
            coalesce((select nombre from public.profiles where id = old.responsable), 'sin asignar')
            || ' → ' ||
            coalesce((select nombre from public.profiles where id = new.responsable), 'sin asignar'));
  end if;

  if new.nombre   is distinct from old.nombre   then v_datos := array_append(v_datos, 'nombre'); end if;
  if new.cif      is distinct from old.cif      then v_datos := array_append(v_datos, 'CIF'); end if;
  if new.sector   is distinct from old.sector   then v_datos := array_append(v_datos, 'sector'); end if;
  if new.contacto is distinct from old.contacto then v_datos := array_append(v_datos, 'contacto'); end if;
  if new.email    is distinct from old.email    then v_datos := array_append(v_datos, 'email'); end if;
  if new.telefono is distinct from old.telefono then v_datos := array_append(v_datos, 'teléfono'); end if;

  if array_length(v_datos, 1) > 0 then
    insert into public.historial (empresa_id, empresa_nombre, usuario_id, usuario_nombre, accion, detalle)
    values (new.id, new.nombre, v_uid, v_nombre, 'datos', 'Actualizado: ' || array_to_string(v_datos, ', '));
  end if;

  return new;
end;
$$;

-- Mantiene la marca de "histórica" según haya prácticas registradas o no
create or replace function public.practicas_sync_historica()
returns trigger
language plpgsql security definer
set search_path to 'public'
as $$
declare v_emp public.empresas.id%type;
begin
  v_emp := coalesce(new.empresa_id, old.empresa_id);
  perform set_config('crm.sistema', '1', true);
  update public.empresas
     set historica = exists (select 1 from public.practicas where empresa_id = v_emp)
   where id = v_emp;
  perform set_config('crm.sistema', '', true);
  return null;
end;
$$;

-- Datos para el ranking (historial + empresas) hasta una fecha
create or replace function public.ranking_datos(p_hasta date)
returns jsonb
language sql stable security definer
set search_path to 'public'
as $$
  select jsonb_build_object(
    'hist', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', h.id, 'empresa_id', h.empresa_id, 'usuario_id', h.usuario_id, 'usuario_nombre', h.usuario_nombre,
        'accion', h.accion, 'estado_nuevo', h.estado_nuevo, 'creado', h.creado) order by h.creado, h.id)
      from public.historial h
      where h.creado < (p_hasta + 1)
    ), '[]'::jsonb),
    'empresas', coalesce((
      select jsonb_agg(jsonb_build_object('id', e.id, 'nombre', e.nombre, 'responsable', e.responsable, 'estado', e.estado))
      from public.empresas e
    ), '[]'::jsonb)
  )
  where auth.uid() is not null;
$$;

-- Un admin pone una contraseña temporal a otro usuario
create or replace function public.admin_poner_contrasena(p_usuario uuid, p_contrasena text)
returns void
language plpgsql security definer
set search_path to 'public', 'extensions'
as $$
begin
  if not public.is_admin() then
    raise exception 'Solo un admin puede cambiar contraseñas de otros usuarios';
  end if;
  if p_usuario = auth.uid() then
    raise exception 'Para tu propia contraseña usa «Cambiar mi contraseña»';
  end if;
  if length(coalesce(p_contrasena, '')) < 6 then
    raise exception 'La contraseña necesita al menos 6 caracteres';
  end if;

  update auth.users
     set encrypted_password = crypt(p_contrasena, gen_salt('bf')),
         updated_at = now()
   where id = p_usuario;

  if not found then
    raise exception 'No existe ese usuario';
  end if;
end;
$$;

-- Hook de registro: rechaza emails mal formados o de dominios desechables
create or replace function public.hook_antes_de_crear_usuario(event jsonb)
returns jsonb
language plpgsql security definer
set search_path to ''
as $$
declare
  v_email   text := lower(trim(coalesce(event -> 'user' ->> 'email', '')));
  v_dominio text;
begin
  if v_email = '' then
    return jsonb_build_object('error', jsonb_build_object(
      'http_code', 400, 'message', 'Hace falta un email para registrarse.'));
  end if;

  if length(v_email) > 254
     or v_email !~ '^[a-z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*\.[a-z]{2,}$' then
    return jsonb_build_object('error', jsonb_build_object(
      'http_code', 400, 'message', 'Ese email no tiene un formato válido.'));
  end if;

  v_dominio := split_part(v_email, '@', 2);

  if exists (
    select 1 from public.dominios_bloqueados b
    where v_dominio = b.dominio or v_dominio like '%.' || b.dominio
  ) then
    return jsonb_build_object('error', jsonb_build_object(
      'http_code', 400,
      'message', 'No se admiten correos temporales o desechables. Usa tu email personal o el de la universidad.'));
  end if;

  return '{}'::jsonb;
end;
$$;

-- Permisos del hook: solo lo ejecuta el sistema de autenticación de Supabase
grant usage on schema public to supabase_auth_admin;
grant execute on function public.hook_antes_de_crear_usuario(jsonb) to supabase_auth_admin;
revoke execute on function public.hook_antes_de_crear_usuario(jsonb) from authenticated, anon, public;
grant select on public.dominios_bloqueados to supabase_auth_admin;

-- admin_poner_contrasena solo para usuarios con sesión
revoke execute on function public.admin_poner_contrasena(uuid, text) from anon, public;
grant execute on function public.admin_poner_contrasena(uuid, text) to authenticated;


-- ---------------------------------------------------------------------
--  3. Triggers
-- ---------------------------------------------------------------------

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create trigger empresas_before_update
  before update on public.empresas
  for each row execute function public.empresas_guard();

create trigger empresas_after_change
  after insert or update on public.empresas
  for each row execute function public.historial_log();

create trigger practicas_sync
  after insert or update or delete on public.practicas
  for each row execute function public.practicas_sync_historica();


-- ---------------------------------------------------------------------
--  4. Seguridad (RLS): quién puede ver y tocar qué
-- ---------------------------------------------------------------------

alter table public.profiles            enable row level security;
alter table public.empresas            enable row level security;
alter table public.historial           enable row level security;
alter table public.practicas           enable row level security;
alter table public.dominios_bloqueados enable row level security;  -- sin políticas: nadie la lee desde la app

-- profiles: todos ven a todos; solo admin cambia roles
create policy profiles_select       on public.profiles for select to authenticated using (true);
create policy profiles_update_admin on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- empresas: todos ven todas (para avisar de CIF duplicados y saber quién lleva cada una);
-- cada miembro edita solo las suyas; crear: admin o asignándosela a sí mismo; borrar: solo admin
create policy empresas_select on public.empresas for select to authenticated using (true);
create policy empresas_insert on public.empresas for insert to authenticated with check (public.is_admin() or responsable = auth.uid());
create policy empresas_update on public.empresas for update to authenticated using (public.is_admin() or responsable = auth.uid());
create policy empresas_delete on public.empresas for delete to authenticated using (public.is_admin());

-- historial: lo escriben los triggers; se ve lo propio o lo de tus empresas (admin, todo); borra admin
create policy historial_select on public.historial for select to authenticated using (
  public.is_admin()
  or usuario_id = auth.uid()
  or exists (select 1 from public.empresas e where e.id = historial.empresa_id and e.responsable = auth.uid())
);
create policy historial_delete on public.historial for delete to authenticated using (public.is_admin());

-- practicas: todos ven; solo admin crea, edita y borra
create policy practicas_ver    on public.practicas for select to authenticated using (true);
create policy practicas_crear  on public.practicas for insert to authenticated with check (public.is_admin());
create policy practicas_editar on public.practicas for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy practicas_borrar on public.practicas for delete to authenticated using (public.is_admin());
